/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidatorsImport } from './routes/validators'
import { Route as AddImport } from './routes/add'
import { Route as IndexImport } from './routes/index'
import { Route as ValidatorsValidatorIdImport } from './routes/validators_.$validatorId'

// Create/Update Routes

const ValidatorsRoute = ValidatorsImport.update({
  path: '/validators',
  getParentRoute: () => rootRoute,
} as any)

const AddRoute = AddImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ValidatorsValidatorIdRoute = ValidatorsValidatorIdImport.update({
  path: '/validators/$validatorId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddImport
      parentRoute: typeof rootRoute
    }
    '/validators': {
      id: '/validators'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsImport
      parentRoute: typeof rootRoute
    }
    '/validators/$validatorId': {
      id: '/validators/$validatorId'
      path: '/validators/$validatorId'
      fullPath: '/validators/$validatorId'
      preLoaderRoute: typeof ValidatorsValidatorIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AddRoute,
  ValidatorsRoute,
  ValidatorsValidatorIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/validators",
        "/validators/$validatorId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add": {
      "filePath": "add.tsx"
    },
    "/validators": {
      "filePath": "validators.tsx"
    },
    "/validators/$validatorId": {
      "filePath": "validators_.$validatorId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
