/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Name and account defined as a donation target
type DonationAccount struct {
	// Algorand account address for this donation account
	Address string `json:"address"`
	// url of image for this donation target
	Image string `json:"image"`
	Name  string `json:"name"`
	// name of NFD for this cause
	Nfd string `json:"nfd"`
}
