/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinkAddressRequestBody struct {
	// Address(es) to link to the NFD (must be able to sign for each)
	Address []string `json:"address"`
	// Address that will be signing the returned transactions.  Should be owner of NFD
	Sender string `json:"sender"`
}
