/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetQuoteResponseBody struct {
	// extra needed to cover MBR (if necessary) - price already includes this amount
	CarryCost int64 `json:"carryCost"`
	// whether the nfd exists. if so, cost is renewal, otherwise mint (including carry)
	Exists bool `json:"exists"`
	// if nfd is in auction pricing for given buyer
	InAuction bool `json:"inAuction"`
	// whether the (existing) nfd is expired
	IsExpired bool `json:"isExpired"`
	// price in microAlgo for 1 year w/ carry cost (if needs minted) added in. subtract carry cost for per-year cost
	Price int64 `json:"price"`
}
