/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// ConsensusRecord contains information about an account that participated in consensus
type ConsensusRecord struct {
	Account       string    `json:"account"`
	LastPropBlock int64     `json:"lastPropBlock,omitempty"`
	LastPropTime  time.Time `json:"lastPropTime,omitempty"`
	LastVoteBlock int64     `json:"lastVoteBlock,omitempty"`
	LastVoteTime  time.Time `json:"lastVoteTime,omitempty"`
	LinkType      string    `json:"linkType,omitempty"`
	OwnerAccount  string    `json:"ownerAccount"`
	PctOfOnline   float64   `json:"pctOfOnline"`
	Proposals     int64     `json:"proposals,omitempty"`
	Rank          int64     `json:"rank,omitempty"`
	Votes         int64     `json:"votes,omitempty"`
}
