/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// NFDAnalyticEvent contains a price history record for a point in time of an NFD
type NfdAnalyticEvent struct {
	Block int32  `json:"block,omitempty"`
	Buyer string `json:"buyer,omitempty"`
	// extra amount paid to cover minimum balance requirements - add to price to determine total amount paid
	CarryCost int32  `json:"carryCost,omitempty"`
	Category  string `json:"category,omitempty"`
	// NFD current owner - if set via includeOwner property
	CurrentOwner string   `json:"currentOwner,omitempty"`
	Event        string   `json:"event,omitempty"`
	GroupID      string   `json:"groupID,omitempty"`
	MetaTags     []string `json:"metaTags,omitempty"`
	// NFD Name
	Name     string `json:"name,omitempty"`
	Note     string `json:"note,omitempty"`
	SaleType string `json:"saleType,omitempty"`
	Seller   string `json:"seller,omitempty"`
}
