/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TotalsOkResponseBodyContractTotals struct {
	// Contract versions
	AllVersions map[string]int64 `json:"allVersions,omitempty"`
	// Contract versions
	MajorVersions map[string]int64 `json:"majorVersions,omitempty"`
}
