/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RenewRequestBody struct {
	// Offer price in ALGO. Expiration time set prorated based on amount paid vs fixed per-year cost when years argument is used
	AlgoOffer int64 `json:"algoOffer,omitempty"`
	// Address paying/signing for minting transaction
	Buyer string `json:"buyer"`
	Name  string `json:"name"`
	// Number of years until expiration, 1 yr minimum, 20 max, extending renewal date - sets price in multiples of 1 year. If not current owner and expired, only 1 year is allowed
	Years int64 `json:"years,omitempty"`
}
