/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// NFD contains all known information about an NFD record
type Nfd struct {
	// NFD Application ID
	AppID int64 `json:"appID,omitempty"`
	// NFD ASA ID
	AsaID int64 `json:"asaID,omitempty"`
	// Whether the verified Avatar set in this NFD is newer (arc19) then is set into the NFD. This will only be present on direct NFD fetch and if true
	AvatarOutdated bool `json:"avatarOutdated,omitempty"`
	// Verified Algorand addresses for this NFD
	CaAlgo []string `json:"caAlgo,omitempty"`
	// Cache-Control header
	CacheControl string `json:"cache-control,omitempty"`
	Category     string `json:"category,omitempty"`
	// Round this data was last fetched from
	CurrentAsOfBlock int64 `json:"currentAsOfBlock,omitempty"`
	// account wallets should send funds to - precedence is: caAlgo[0], unverifiedCaAlgo[0], owner
	DepositAccount string `json:"depositAccount,omitempty"`
	// ETag
	Etag    string `json:"etag,omitempty"`
	Expired bool   `json:"expired,omitempty"`
	// Tags set by the system for tracking/analytics
	MetaTags   []string `json:"metaTags,omitempty"`
	Name       string   `json:"name"`
	NfdAccount string   `json:"nfdAccount,omitempty"`
	// Owner of NFD
	Owner string `json:"owner,omitempty"`
	// NFD Application ID of Parent if this is a segment
	ParentAppID int64          `json:"parentAppID,omitempty"`
	Properties  *NfdProperties `json:"properties,omitempty"`
	// Reserved owner of NFD
	ReservedFor string `json:"reservedFor,omitempty"`
	SaleType    string `json:"saleType,omitempty"`
	// amount NFD is being sold for (microAlgos)
	SellAmount int64 `json:"sellAmount,omitempty"`
	// RecipientUid of NFD sales
	Seller         string `json:"seller,omitempty"`
	SigNameAddress string `json:"sigNameAddress,omitempty"`
	State          string `json:"state,omitempty"`
	// Tags assigned to this NFD
	Tags          []string  `json:"tags,omitempty"`
	TimeChanged   time.Time `json:"timeChanged,omitempty"`
	TimeCreated   time.Time `json:"timeCreated,omitempty"`
	TimeExpires   time.Time `json:"timeExpires,omitempty"`
	TimePurchased time.Time `json:"timePurchased,omitempty"`
	// Unverified (non-algo) Crypto addresses for this NFD
	UnverifiedCa map[string][]string `json:"unverifiedCa,omitempty"`
	// Unverified Algorand addresses for this NFD
	UnverifiedCaAlgo []string `json:"unverifiedCaAlgo,omitempty"`
}
