/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PartnerKickoffRequestBody struct {
	Buyer string `json:"buyer"`
	// a convenience fee percentage to add 'on top' of the NFD price - 10 is 1%, 150 is 15%
	ConveniencePct int64  `json:"conveniencePct,omitempty"`
	Name           string `json:"name"`
}
