/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerifyRequestRequestBody struct {
	// User defined field name to verify
	FieldToVerify string `json:"fieldToVerify"`
	Name          string `json:"name"`
	// Sender of transaction - needs to be owner of NFD
	Sender string `json:"sender"`
}
