/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OfferRequestBody struct {
	// Amount in microAlgo to sell the NFD for.  1 ALGO is 1,000,000 microAlgo. 1 ALGO minimum, 100 million maximum.
	Offer int32 `json:"offer"`
	// Whether to pay the offer amount + fees to the account the NFD is reserved for.  Equivalent to 'gifting' the NFD
	PayReceiver bool   `json:"payReceiver,omitempty"`
	ReservedFor string `json:"reservedFor,omitempty"`
	// Sender of transaction - needs to be owner of NFD
	Sender string `json:"sender"`
}
