/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NfdAuctionAndPrice struct {
	AuctionInfo *NfdAuction `json:"auctionInfo"`
	// Change in price per minute
	ChangePerMinute int32 `json:"changePerMinute,omitempty"`
	// Minutes elapsed so far in Auction
	ElapsedMinutes int64 `json:"elapsedMinutes,omitempty"`
	// Current price in microAlgos
	Price int32 `json:"price,omitempty"`
	// Total number of minutes in Auction
	TotalMinutes int64 `json:"totalMinutes,omitempty"`
}
