/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type NfdAuction struct {
	// Price in microAlgos
	CeilingPrice int32 `json:"ceilingPrice"`
	// Price in microAlgos
	CurrentPrice int32     `json:"currentPrice,omitempty"`
	EndTime      time.Time `json:"endTime"`
	// Price in microAlgos
	FloorPrice int32     `json:"floorPrice"`
	Name       string    `json:"name"`
	NewEndTime time.Time `json:"newEndTime,omitempty"`
	// Escrowed floor price in microAlgos
	NewFloorPrice int32     `json:"newFloorPrice,omitempty"`
	StartTime     time.Time `json:"startTime"`
}
