/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NfdV2SearchRecords struct {
	// Not returned, used in tagging for response to indicate if-none-match etag matched
	MatchCheck string       `json:"match-check,omitempty"`
	Nfds       *[]NfdRecord `json:"nfds"`
	// total number of results, with data containing paged amount based on offset/limit
	Total int64 `json:"total"`
}
