/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Whether NFD NFT ASA ID is for authentic NFD
type IsValidAsaResponseBody struct {
	AppID   int32  `json:"appID"`
	IsValid bool   `json:"isValid"`
	Message string `json:"message"`
	Name    string `json:"name"`
}
