/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type VaultOptInLockRequestBody struct {
	// Whether to lock (true), or unlock (false)
	Lock bool `json:"lock"`
	// If unlocking vault, specify a time to automatically re-lock the vault.  This allows an unlock that only lasts for a paticular amount of time.  The time specifies the moment the vault should re-lock.
	ReLockAt time.Time `json:"reLockAt,omitempty"`
	// Sender of transaction - needs to be owner of NFD
	Sender string `json:"sender"`
}
