/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SegmentLockRequestBody struct {
	// Whether to lock (true), or unlock (false)
	Lock bool `json:"lock"`
	// amount users minting off the segment have to pay to mint in USD (in cents - ie: 300 = $3.00). Set to 0 if locking
	SellAmount int64 `json:"sellAmount"`
	// Sender of transaction - needs to be owner of NFD
	Sender string `json:"sender"`
}
