/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PurchaseRequestBody struct {
	Buyer string `json:"buyer"`
	// Amount in microAlgo to purchase/claim the NFD for
	Offer int64 `json:"offer"`
}
