/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RateLimited struct {
	Limit         int64 `json:"limit"`
	SecsRemaining int64 `json:"secsRemaining"`
}
