/*
 * NFD Management Service
 *
 * Service for querying and managing NFDs
 *
 * API version: 1.0
 * Contact: feedback@txnlab.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TotalsOkResponseBody struct {
	ContractTotals *TotalsOkResponseBodyContractTotals `json:"contractTotals"`
	// NFDs that have expired
	ExpiredTotal int64 `json:"expiredTotal"`
	ForSale      int64 `json:"forSale"`
	// Not returned, used in tagging for response to indicate if-none-match etag matched
	MatchCheck    string                            `json:"match-check,omitempty"`
	MintedTotals  *TotalsOkResponseBodyMintedTotals `json:"mintedTotals"`
	SegmentTotals *TotalsOkResponseBodyMintedTotals `json:"segmentTotals"`
	SoldTotals    *TotalsOkResponseBodyMintedTotals `json:"soldTotals"`
	Total         int64                             `json:"total"`
	TotalSegments int64                             `json:"totalSegments"`
	UniqueOwners  int64                             `json:"uniqueOwners"`
}
