name: Playwright Tests
on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
      # - 'dev'

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright and its dependencies
        run: pnpm --filter ./ui exec playwright install --with-deps

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pipx
        run: python3 -m pip install --user pipx

      - name: Ensure Pipx is on PATH
        run: python3 -m pipx ensurepath

      - name: Install Algokit
        run: pipx install algokit

      - name: Start local Algorand network
        run: algokit localnet start

      - name: Bootstrap the validator
        run: pnpm run bootstrap

      - name: Run Playwright tests
        run: pnpm --filter ./ui exec playwright test
